include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # İsterseniz burada bazı kuralları görmezden gelebilirsiniz
    # avoid_print: ignore 

  enable-experiment:
    - non-nullable

linter:
  rules:
    # İsterseniz burada bazı kuralları kapatabilirsiniz
    # - avoid_print