include: package:very_good_analysis/analysis_options.yaml

analyzer:
  enable-experiment: []
  errors:
    # İsterseniz burada bazı kuralları görmezden gelebilirsiniz
    # avoid_print: ignore 

linter:
  rules:
    # İsterseniz burada bazı kuralları kapatabilirsiniz
    # - avoid_print