[pytest]
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:.*SwigPyPacked has no __module__ attribute.*:DeprecationWarning
    ignore:.*SwigPyObject has no __module__ attribute.*:DeprecationWarning
    ignore:.*swigvarlink has no __module__ attribute.*:DeprecationWarning
